import os
import sys
import cv2
import numpy as np
import matplotlib.pyplot as plt
import scipy.io as sio

def main():
    """
    Main orchestrator for Part 3: Out-of-Plane Object Removal.
    Reads the 3D transformations generated by Part 2, uses RANSAC to find the 
    dominant document plane, filters out foreground occlusions, and splats 
    the cleaned points back onto the 2D template.
    """
    # 1. Handle command-line arguments with defaults
    if len(sys.argv) == 1:
        print("No arguments provided. Using default dataset paths...")
        path_to_refimg = "../part2/data/plondres_template"
        path_images_dir = "../part2/data/plondres_sequence"
        path_transform_dir = "../part2/data/plondres_output"
        path_final_output = "data/cleaned_output"
    elif len(sys.argv) == 5:
        path_to_refimg = sys.argv[1]
        path_images_dir = sys.argv[2]
        path_transform_dir = sys.argv[3]
        path_final_output = sys.argv[4]
    else:
        print("Usage: python main3.py [path_refimg path_images path_transforms path_final_output]")
        sys.exit(1)

    # prevent crash by ensuring output directory exists
    os.makedirs(path_final_output, exist_ok=True)

    # 2. Load template data
    print("Loading Template Data...")
    tim = cv2.cvtColor(
        cv2.imread(os.path.join(path_to_refimg,'templatergb.jpg')),
        cv2.COLOR_BGR2RGB
    )

    mat = sio.loadmat(os.path.join(path_to_refimg,'templatedepth.mat'))
    depth = mat['depth']
    K = mat['K']

    h, w = depth.shape
    fx, fy = K[0,0], K[1,1]
    cx, cy = K[0,2], K[1,2]

    # extract valid 3D points from template
    ys, xs = np.meshgrid(np.arange(h), np.arange(w), indexing='ij')
    z = depth.reshape(-1)
    valid = z > 0

    x = (xs.reshape(-1) - cx) * z / fx
    y = (ys.reshape(-1) - cy) * z / fy

    ref_pts = np.stack([x, y, z], axis=1)[valid]

    # 3. Find document plane via RANSAC
    print(f"Computing dominant 3D plane (Document Surface)...")
    plane, mask = get_best_plane(ref_pts)
    n, p = plane
    print(f"Plane found with {np.sum(mask)} inliers.")

    # 4. Process sequence frames and remove objects
    ii = 0
    image_files = sorted(f for f in os.listdir(path_images_dir) if f.lower().endswith(('.jpg', '.png')))
    
    for fname in image_files:
        ii += 1
        print(f"Processing frame{ii}/{len(image_files)}: {fname}...")

        # read RGB
        im_rgb = cv2.imread(os.path.join(path_images_dir, fname))
        im = cv2.cvtColor(im_rgb, cv2.COLOR_BGR2RGB)

        # load per-frame transform
        name, _ = os.path.splitext(fname)
        number = name.split('_')[-1]
        transform_file = os.path.join(path_transform_dir, f"transform_{number}.mat")
        
        try:
            data = sio.loadmat(transform_file)
            scale, R, T = data['scale'], data['R'], data['T'].reshape(3)
        except FileNotFoundError:
            print(f"Transform missing for {fname}. Did you run Part 2?")
            continue

        # load depth and intrinsics
        mat = sio.loadmat(os.path.join(path_images_dir, f"{name}.mat"))
        depth = mat['depth']
        K = mat['K']

        h, w = depth.shape
        fx, fy = K[0,0], K[1,1]
        cx, cy = K[0,2], K[1,2]

        # backproject current frame to 3D
        ys, xs = np.meshgrid(np.arange(h), np.arange(w), indexing='ij')
        z = depth.reshape(-1)
        valid = z > 0

        x = (xs.reshape(-1) - cx) * z / fx
        y = (ys.reshape(-1) - cy) * z / fy

        pc = np.stack([x, y, z], axis=1)[valid]
        colors = im[ys.reshape(-1)[valid], xs.reshape(-1)[valid]]

        # transform points into the template coordinate frame
        pts = scale * (pc @ R.T) + T

        # PLANE FILTERING (OCCLUSION REMOVAL)
        # discard points that are too far from the computed document plane
        dist = np.abs((pts - p) @ n)
        mask = dist < 0.04  # distance threshold

        pts = pts[mask]
        colors = colors[mask]

        if len(pts) == 0:
            print(f"Frame {ii}: no plane points")
            continue

        # project cleaned points back into 2D template perspective
        img_pts, _ = cv2.projectPoints(
            pts.astype(np.float32),
            np.zeros((3,1)),
            np.zeros((3,1)),
            K.astype(np.float32),
            None
        )
        img_pts = img_pts.reshape(-1, 2)

        # DENSE RASTERIZATION (Z-BUFFERING & SPLATTING)
        template_equiv = tim.copy()
        zbuf = np.full((h, w), np.inf)

        # splat size: 3x3 neighborhood to fill holes
        splat = [-1, 0, 1]

        for (u, v), z_val, color in zip(img_pts, pts[:,2], colors):
            u = int(round(u))
            v = int(round(v))
            for du in splat:
                for dv in splat:
                    uu = u + du
                    vv = v + dv
                    if 0 <= uu < w and 0 <= vv < h:
                        if z_val < zbuf[vv, uu]:
                            zbuf[vv, uu] = z_val
                            template_equiv[vv, uu] = color

        

        output_file = os.path.join(path_final_output, f"cleaned_frame_{ii:04d}.png")
        plt.imsave(output_file, template_equiv)

    print("Part 3 pipeline complete! Cleaned images saved.")


def get_best_plane(tpc):
    """
    Finds the mathematical plane of the document surface within the 3D point cloud 
    using a custom RANSAC algorithm.
    Returns the plane normal (n), a point on the plane (p), and an inlier mask.
    """
    max_tries = 1000
    error_threshold = 0.02

    best_plane = None
    best_inliers_count = 0
    inliers_mask = None

    points = tpc.reshape(-1, 3)
    
    for _ in range(max_tries):
        # sample 3 random points to define a plane
        random_indices = np.random.choice(points.shape[0], size=3, replace=False)
        p1, p2, p3 = points[random_indices[0]], points[random_indices[1]], points[random_indices[2]]

        v1 = p2 - p1
        v2 = p3 - p1
        n = np.cross(v1, v2)
        
        # skip if points are collinear
        if np.linalg.norm(n) == 0:
            continue
          
        n = n / np.linalg.norm(n) 

        # calculate distance from all points to the proposed plane
        distances = np.abs( np.dot(points - p1, n) )

        current_inliers_mask = distances < error_threshold
        inliers_count = np.sum(current_inliers_mask)

        if inliers_count > best_inliers_count:
            best_inliers_count = inliers_count
            best_plane = (n, p1)
            inliers_mask = current_inliers_mask

    return best_plane, inliers_mask


if __name__ == "__main__":
    main()